name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t asifhajiyev/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true asifhajiyev/react-test npm test

      - run: docker build -t asifhajiyev/multi-client-10-14 ./client
      - run: docker build -t asifhajiyev/multi-nginx-10-14 ./nginx
      - run: docker build -t asifhajiyev/multi-server-10-14 ./server
      - run: docker build -t asifhajiyev/multi-worker-10-14 ./worker

      - run: docker push asifhajiyev/multi-client-10-14
      - run: docker push asifhajiyev/multi-nginx-10-14
      - run: docker push asifhajiyev/multi-server-10-14
      - run: docker push asifhajiyev/multi-worker-10-14

